spring.application.name=streamix
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=streamix
spring.datasource.password=root
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=8082
spring.security.user.name=varsh
spring.security.user.password=varsh123
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.jdbc.fetch_size = 50


# Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging.level.org.hibernate.SQL=DEBUG

#for thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false