#spring.application.name=streamix
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=varsh 
spring.datasource.password=root
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=8081


#for thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html